name = "og"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-11-11"
env = { }

kv_namespaces = [
  { binding = "WORKER_OG", id = "bdf583f7be3f4bc08416bff357caec5f" }
]

routes = [
  { pattern = "workers.vinh.dev/og*", zone_name = "vinh.dev" }
]

[placement]
mode = "smart"

[triggers]
crons = [ ]

[observability]
enabled = true
