name = "vinh-dev-worker"
main = "src/index.ts"
compatibility_date = "2024-11-11"
compatibility_flags = [ "nodejs_compat_v2" ]
assets = { directory = "public", binding = "ASSETS" }
minify = true
routes = [ { pattern = "worker.vinh.dev/*", zone_name = "vinh.dev" } ]

[build]
watch_dir = "public"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
SITE_URL = "https://vinh.dev"
