name = "og"
main = "src/index.ts"
compatibility_date = "2023-08-23"
env = { }

kv_namespaces = [
  { binding = "WORKER_OG", id = "bdf583f7be3f4bc08416bff357caec5f" }
]

routes = [
  { pattern = "worker.vinh.dev/og*", zone_name = "vinh.dev" }
]

[triggers]
crons = [ ]
