name = "workers"
main = "src/index.ts"
compatibility_date = "2023-08-23"
usage_model = "bundled"
env = { }

[route]
pattern = "workers.vinh.dev/og"
zone_name = ""
script = "workers"

[triggers]
crons = [ ]
